<?php

namespace Database\Seeders;

use App\Models\PageSetting;
use Illuminate\Database\Seeder;

class PageSettingSeeder extends Seeder
{
    public function run(): void
    {
        $pages = [
            ['page_key' => 'home',                              'page_name' => 'Home',                          'meta_title' => 'Zalgo Infotech - IT Solutions & Web Development',                     'meta_description' => 'Zalgo Infotech delivers cutting-edge web development, AI solutions, and digital marketing services to help businesses grow and succeed online.'],
            ['page_key' => 'about',                             'page_name' => 'About Us',                      'meta_title' => 'About Us - Zalgo Infotech',                                           'meta_description' => 'Learn about Zalgo Infotech, our mission, our team, and how we help businesses thrive through innovative technology solutions.'],
            ['page_key' => 'contact',                           'page_name' => 'Contact',                       'meta_title' => 'Contact Us - Zalgo Infotech',                                         'meta_description' => 'Get in touch with the Zalgo Infotech team for inquiries, project discussions, or support. We are here to help.'],
            ['page_key' => 'pricing',                           'page_name' => 'Pricing',                       'meta_title' => 'Pricing Plans - Zalgo Infotech',                                      'meta_description' => 'Explore our flexible and transparent pricing plans designed to fit businesses of all sizes. Find the right plan for your needs.'],
            ['page_key' => 'faq',                               'page_name' => 'FAQ',                           'meta_title' => 'Frequently Asked Questions - Zalgo Infotech',                         'meta_description' => 'Find answers to the most commonly asked questions about our services, processes, and technology solutions.'],
            ['page_key' => 'testimonial',                       'page_name' => 'Testimonials',                  'meta_title' => 'Client Testimonials - Zalgo Infotech',                                'meta_description' => 'Read verified reviews from our clients on Clutch and Google. See why businesses trust Zalgo Infotech for their digital needs.'],
            ['page_key' => 'blog',                              'page_name' => 'Blog',                          'meta_title' => 'Blog - Zalgo Infotech',                                               'meta_description' => 'Stay up to date with the latest insights, tips, and news on web development, AI, digital marketing, and more from our experts.'],
            ['page_key' => 'casestudy',                         'page_name' => 'Case Studies',                  'meta_title' => 'Case Studies - Zalgo Infotech',                                       'meta_description' => 'Explore our portfolio of successful projects and discover how Zalgo Infotech has helped clients achieve their business goals.'],
            ['page_key' => 'career',                            'page_name' => 'Career',                        'meta_title' => 'Careers at Zalgo Infotech',                                           'meta_description' => 'Join the Zalgo Infotech team! Explore exciting career opportunities and be part of a team building innovative technology solutions.'],
            ['page_key' => 'portfolio',                         'page_name' => 'Portfolio',                     'meta_title' => 'Our Portfolio - Zalgo Infotech',                                      'meta_description' => 'Browse our portfolio of web development, mobile app, and digital marketing projects delivered for clients worldwide.'],
            // Services
            ['page_key' => 'web.development',                   'page_name' => 'Web Development',               'meta_title' => 'Web Development Services - Zalgo Infotech',                           'meta_description' => 'Custom web development solutions built for performance, scalability, and exceptional user experience. From landing pages to enterprise platforms.'],
            ['page_key' => 'cms.development',                   'page_name' => 'CMS Development',               'meta_title' => 'CMS Development Services - Zalgo Infotech',                           'meta_description' => 'Professional CMS development services to build flexible, easy-to-manage content platforms tailored to your business needs.'],
            ['page_key' => 'react.development',                 'page_name' => 'ReactJS Development',           'meta_title' => 'ReactJS Development Services - Zalgo Infotech',                       'meta_description' => 'Expert ReactJS development services for fast, dynamic, and interactive web applications that delight users.'],
            ['page_key' => 'shopify.development',               'page_name' => 'Shopify Development',           'meta_title' => 'Shopify Development Services - Zalgo Infotech',                       'meta_description' => 'Custom Shopify store development and optimization to help you launch and grow your e-commerce business with ease.'],
            ['page_key' => 'nodejs.development',                'page_name' => 'NodeJS Development',            'meta_title' => 'NodeJS Development Services - Zalgo Infotech',                        'meta_description' => 'High-performance NodeJS development for scalable backend systems, APIs, and real-time applications.'],
            ['page_key' => 'wordpressdevelopment.development',  'page_name' => 'WordPress Development',         'meta_title' => 'WordPress Development Services - Zalgo Infotech',                     'meta_description' => 'Professional WordPress development — custom themes, plugins, and performance-optimized websites for your business.'],
            ['page_key' => 'ecommerce.development',             'page_name' => 'E-Commerce Development',        'meta_title' => 'E-Commerce Development Services - Zalgo Infotech',                    'meta_description' => 'End-to-end e-commerce development services including store setup, payment integration, and conversion optimization.'],
            ['page_key' => 'python.development',                'page_name' => 'Python Development',            'meta_title' => 'Python Development Services - Zalgo Infotech',                        'meta_description' => 'Expert Python development for web apps, data pipelines, automation, and machine learning solutions.'],
            ['page_key' => 'ai.development',                    'page_name' => 'AI Development',                'meta_title' => 'AI Development Services - Zalgo Infotech',                            'meta_description' => 'Cutting-edge AI and machine learning solutions to automate processes, gain insights, and power intelligent applications.'],
            ['page_key' => 'laravel.development',               'page_name' => 'Laravel Development',           'meta_title' => 'Laravel Development Services - Zalgo Infotech',                       'meta_description' => 'Robust and scalable Laravel web application development with clean code, security best practices, and rapid delivery.'],
            ['page_key' => 'maintenanceservices.development',   'page_name' => 'Maintenance Services',          'meta_title' => 'Website Maintenance Services - Zalgo Infotech',                       'meta_description' => 'Keep your website secure, up-to-date, and performing at its best with our professional maintenance and support services.'],
            ['page_key' => 'seoservices.development',           'page_name' => 'SEO Services',                  'meta_title' => 'SEO Services - Zalgo Infotech',                                       'meta_description' => 'Data-driven SEO strategies to improve your search rankings, drive organic traffic, and grow your business online.'],
            ['page_key' => 'digitalservices.development',       'page_name' => 'Digital Marketing',             'meta_title' => 'Digital Marketing Services - Zalgo Infotech',                         'meta_description' => 'Comprehensive digital marketing services including PPC, social media, content marketing, and analytics to grow your brand.'],
            ['page_key' => 'web.design',                        'page_name' => 'Web Design',                    'meta_title' => 'Web Design Services - Zalgo Infotech',                                'meta_description' => 'Creative and conversion-focused web design services that make your brand stand out and engage your audience.'],
            // Hire Developers
            ['page_key' => 'hireweb.developer',                 'page_name' => 'Hire Web Developer',            'meta_title' => 'Hire Web Developers - Zalgo Infotech',                                'meta_description' => 'Hire skilled and experienced web developers from Zalgo Infotech to build high-quality websites and web applications.'],
            ['page_key' => 'hirewordpressdeveloper',            'page_name' => 'Hire WordPress Developer',      'meta_title' => 'Hire WordPress Developers - Zalgo Infotech',                          'meta_description' => 'Hire expert WordPress developers for custom themes, plugins, and full website builds tailored to your requirements.'],
            ['page_key' => 'hirelaraveldeveloper',              'page_name' => 'Hire Laravel Developer',        'meta_title' => 'Hire Laravel Developers - Zalgo Infotech',                            'meta_description' => 'Hire dedicated Laravel developers to build secure, scalable, and maintainable PHP web applications.'],
            ['page_key' => 'hirenodejsdeveloper',               'page_name' => 'Hire NodeJS Developer',         'meta_title' => 'Hire NodeJS Developers - Zalgo Infotech',                             'meta_description' => 'Hire experienced NodeJS developers to build fast, real-time, and scalable server-side applications.'],
            ['page_key' => 'hirephpdeveloper',                  'page_name' => 'Hire PHP Developer',            'meta_title' => 'Hire PHP Developers - Zalgo Infotech',                                'meta_description' => 'Hire skilled PHP developers to build dynamic, robust, and feature-rich web solutions for your business.'],
            ['page_key' => 'hireaideveloper',                   'page_name' => 'Hire AI Developer',             'meta_title' => 'Hire AI Developers - Zalgo Infotech',                                 'meta_description' => 'Hire expert AI and machine learning developers to build intelligent automation and data-driven solutions.'],
            ['page_key' => 'hirereactjsdeveloper',              'page_name' => 'Hire ReactJS Developer',        'meta_title' => 'Hire ReactJS Developers - Zalgo Infotech',                            'meta_description' => 'Hire dedicated ReactJS developers to build fast, interactive, and modern front-end applications.'],
            ['page_key' => 'hirenextjsdeveloper',               'page_name' => 'Hire NextJS Developer',         'meta_title' => 'Hire NextJS Developers - Zalgo Infotech',                             'meta_description' => 'Hire experienced NextJS developers for server-side rendered and statically generated web applications.'],
            ['page_key' => 'hirepythondeveloper',               'page_name' => 'Hire Python Developer',         'meta_title' => 'Hire Python Developers - Zalgo Infotech',                             'meta_description' => 'Hire expert Python developers for web development, data science, automation, and AI/ML projects.'],
            // Company
            ['page_key' => 'culture-value',                     'page_name' => 'Culture & Values',              'meta_title' => 'Our Culture & Values - Zalgo Infotech',                               'meta_description' => 'Discover the values, culture, and principles that drive us at Zalgo Infotech to deliver excellence in everything we do.'],
            ['page_key' => 'life-zalgoinfotech',                'page_name' => 'Life at Zalgo Infotech',        'meta_title' => 'Life at Zalgo Infotech',                                              'meta_description' => 'Get a glimpse into what it is like to work at Zalgo Infotech — our team, environment, and the people behind our success.'],
            ['page_key' => 'industry',                          'page_name' => 'Industries',                    'meta_title' => 'Industries We Serve - Zalgo Infotech',                                'meta_description' => 'We serve businesses across healthcare, retail, finance, education, and more with tailored technology solutions.'],
            ['page_key' => 'app.intigration',                   'page_name' => 'App Integration',               'meta_title' => 'App Integration Services - Zalgo Infotech',                           'meta_description' => 'Seamlessly connect your tools and platforms with our professional app integration services.'],
            // Case Studies
            ['page_key' => 'bioage',                            'page_name' => 'BioAge Case Study',             'meta_title' => 'BioAge - Case Study | Zalgo Infotech',                                'meta_description' => 'Read how Zalgo Infotech helped BioAge build a scalable digital solution that transformed their operations.'],
            ['page_key' => 'experthe',                          'page_name' => 'Experthe Case Study',           'meta_title' => 'Experthe - Case Study | Zalgo Infotech',                               'meta_description' => 'Discover how Zalgo Infotech delivered a powerful platform for Experthe to connect experts with businesses.'],
            ['page_key' => 'dobramoc',                          'page_name' => 'Dobramoc Case Study',           'meta_title' => 'Dobramoc - Case Study | Zalgo Infotech',                               'meta_description' => 'See how Zalgo Infotech built the Dobramoc platform from concept to a fully functional product.'],
            ['page_key' => 'lifetreeanatomical',                'page_name' => 'Life Tree Anatomical',          'meta_title' => 'Life Tree Anatomical - Case Study | Zalgo Infotech',                   'meta_description' => 'Learn how Zalgo Infotech helped Life Tree Anatomical digitize and scale their educational content platform.'],
            ['page_key' => 'towelsoutlet',                      'page_name' => 'Towels Outlet Case Study',      'meta_title' => 'Towels Outlet - Case Study | Zalgo Infotech',                         'meta_description' => 'Explore how we built a high-converting e-commerce store for Towels Outlet, boosting their online sales.'],
            ['page_key' => 'awakeningthegeniuswithin',          'page_name' => 'Awakening the Genius Within',   'meta_title' => 'Awakening the Genius Within - Case Study | Zalgo Infotech',            'meta_description' => 'Read the case study on how Zalgo Infotech developed a feature-rich learning platform for this coaching brand.'],
            ['page_key' => 'erpsystem',                         'page_name' => 'ERP System Case Study',         'meta_title' => 'ERP System - Case Study | Zalgo Infotech',                            'meta_description' => 'See how Zalgo Infotech built a custom ERP system that streamlined operations and improved efficiency for the client.'],
            ['page_key' => 'labproject',                        'page_name' => 'Lab Project Case Study',        'meta_title' => 'Lab Project - Case Study | Zalgo Infotech',                           'meta_description' => 'Discover how Zalgo Infotech delivered a specialized lab management system with precision and scalability.'],
            ['page_key' => 'lms',                               'page_name' => 'LMS Case Study',                'meta_title' => 'Learning Management System - Case Study | Zalgo Infotech',             'meta_description' => 'Read how Zalgo Infotech developed a powerful LMS platform to deliver engaging online education at scale.'],
            ['page_key' => 'leadmanagement',                    'page_name' => 'Lead Management Case Study',    'meta_title' => 'Lead Management System - Case Study | Zalgo Infotech',                 'meta_description' => 'Explore how we built a custom lead management system that helped our client double their conversion rate.'],
            ['page_key' => 'washingerp',                        'page_name' => 'Washing ERP Case Study',        'meta_title' => 'Washing ERP - Case Study | Zalgo Infotech',                           'meta_description' => 'Learn how Zalgo Infotech designed and delivered a full ERP solution for a laundry and washing business.'],
            ['page_key' => 'financemanagertraining',            'page_name' => 'Finance Manager Training',      'meta_title' => 'Finance Manager Training - Case Study | Zalgo Infotech',              'meta_description' => 'See how Zalgo Infotech built an interactive training platform for finance professionals to upskill efficiently.'],
        ];

        foreach ($pages as $page) {
            PageSetting::updateOrCreate(
                ['page_key' => $page['page_key']],
                $page
            );
        }
    }
}
