// Central map of route paths, mirroring the Laravel route() names 1:1 so the
// URL structure (and SEO) stays identical after the migration.
export const routes = {
  home: "/",
  indexTwo: "/index-two",
  indexThree: "/index-three",
  indexFour: "/index-four",
  indexFive: "/index-five",

  privacy: "/privacy-policy",
  cookie: "/cookie-policy",

  login: "/login",
  register: "/register",

  shop: "/shop",
  shopDetails: "/shop-details",
  cart: "/cart",
  checkout: "/checkout",
  testimonial: "/testimonial",

  pricing: "/pricing",
  about: "/about-us",
  appIntigration: "/app-intigration",
  intigrationDetails: "/intigration-details",
  policyPrivacy: "/policy-privacy",
  faq: "/faq",
  projectDetails: "/project-details",
  serviceDetails: "/service-details",
  industry: "/industry",

  webDevelopment: "/web-development",
  cmsDevelopment: "/cmsdevelopment",
  reactDevelopment: "/reactjsdevelopment",
  shopifyDevelopment: "/shopify",
  nodejsDevelopment: "/nodejs",
  wordpressDevelopment: "/wordpressdevelopment",
  ecommerceDevelopment: "/ecommerce",
  pythonDevelopment: "/python",
  aiDevelopment: "/aidevelopement",
  laravelDevelopment: "/laravel",
  maintenanceServices: "/maintenanceservices",
  wordpressMaintenance: "/wordpress-maintenance",
  seoServices: "/seoservices",
  digitalServices: "/digitalservices",
  cultureValue: "/culturevalue",
  lifeZalgo: "/lifezalgo",

  hireWebDeveloper: "/hirewebdeveloper",
  hireWordpressDeveloper: "/hirewordpressdeveloper",
  hireLaravelDeveloper: "/hirelaraveldeveloper",
  hireNodejsDeveloper: "/hirenodejsdeveloper",
  hirePhpDeveloper: "/hirephpdeveloper",
  hireAiDeveloper: "/hireaideveloper",
  hireReactjsDeveloper: "/hirereactjsdeveloper",
  hireNextjsDeveloper: "/hirenextjsdeveloper",
  hirePythonDeveloper: "/hirepythondeveloper",

  bioage: "/bioage",
  career: "/career",
  experthe: "/experthe",
  dobramoc: "/dobramoc",
  lifetreeanatomical: "/lifetreeanatomical",
  towelsoutlet: "/towelsoutlet",
  awakeningthegeniuswithin: "/awakeningthegeniuswithin",
  erpsystem: "/erpsystem",
  labproject: "/labproject",
  lms: "/lms",
  leadmanagement: "/leadmanagement",
  washingerp: "/washingerp",
  financemanagertraining: "/financemanagertraining",
  kalpmantra: "/kalpmantra",
  shriramexpressnews: "/shriramexpressnews",
  leatherstitch: "/leatherstitch",
  launch: "/launch",

  blog: "/blog",
  casestudy: "/casestudy",
  blogDetails: (slug: string) => `/blog/${slug}`,

  contact: "/contact",
  thankyou: "/thankyou",
} as const;
